services:
  - type: web
    name: dashboard-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - fromDotEnv: true

  - type: web
    name: dashboard-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 10000
    envVars:
      - key: API_URL
        value: https://dashboard-backend.onrender.com # À mettre à jour après le déploiement
      - fromDotEnv: true
